#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_TRAY 101
#define IDM_SETTINGS 102
#define IDM_REGION 103

// Dialogs
#define IDD_MAIN 100
#define IDD_SETTINGS_HOTKEYS 101

// Main Dlg
#define IDC_TITLE_FOLDER 104
#define IDC_FOLDER 105
#define IDC_BROWSE_BTN 106
#define IDC_TITLE_SETTINGS 107
#define IDC_INCLUDEMOUSECURSOR_CHK 108
#define IDC_INCLUDEWINDOWSHADOW_CHK 109
#define IDC_CLEARBACKGROUND_CHK 110
#define IDC_TITLE_MODE 111
#define IDC_MODE_MONITOR 112
#define IDC_MODE_WINDOW 113
#define IDC_MODE_REGION 114
#define IDC_SETTINGS 115
#define IDC_SCREENSHOT 116
#define IDC_EXIT 117

// Settings Dlg
#define IDC_NAV 118
#define IDC_RESET 119
#define IDC_CLOSE 120

#define IDC_TITLE_GENERAL 121
#define IDC_TITLE_LANGUAGE 122
#define IDC_TITLE_FULLSCREEN 123
#define IDC_TITLE_MONITOR 124
#define IDC_TITLE_WINDOW 125
#define IDC_TITLE_REGION 126

#define IDC_ALWAYSONTOP_CHK 127
#define IDC_LOADONSTARTUP_CHK 128
#define IDC_STARTMINIMIZED_CHK 129
#define IDC_CLASSICUI_CHK 130
#define IDC_CHECKUPDATES_CHK 131
#define IDC_LANGUAGE_HINT 132
#define IDC_LANGUAGE 133

#define IDC_FORMAT_HINT 134
#define IDC_FORMAT 135

#define IDC_FILENAME_HINT 136
#define IDC_FILENAME 137

#define IDC_DELAY_HINT 138
#define IDC_DELAY 139

#define IDC_HIDEME_CHK 140
#define IDC_PLAYSOUNDS_CHK 141
#define IDC_DISABLEAEROONWND_CHK 142
#define IDC_COPYTOCLIPBOARD_CHK 143

#define IDC_FULLSCREEN_SHIFT 144
#define IDC_FULLSCREEN_CTRL 145
#define IDC_FULLSCREEN_ALT 146
#define IDC_FULLSCREEN_CB 147

#define IDC_WINDOW_SHIFT 148
#define IDC_WINDOW_CTRL 149
#define IDC_WINDOW_ALT 150
#define IDC_WINDOW_CB 151

#define IDC_REGION_SHIFT 152
#define IDC_REGION_CTRL 153
#define IDC_REGION_ALT 154
#define IDC_REGION_CB 155

// Main Menu
#define IDM_TAKE_FULLSCREEN 156
#define IDM_TAKE_MONITOR 157
#define IDM_TAKE_WINDOW 158
#define IDM_TAKE_REGION 159
#define IDM_EXPLORE 160
#define IDM_EXIT 161
#define IDM_ALWAYSONTOP_CHK 162
#define IDM_HIDEME_CHK 163
#define IDM_CLASSICUI_CHK 164
#define IDM_CHECKUPDATES_CHK 165
#define IDM_WEBSITE 166
#define IDM_CHECKUPDATES 167
#define IDM_ABOUT 168

// Tray Menu
#define IDM_TRAY_SHOW 169
#define IDM_TRAY_TAKE_FULLSCREEN 170
#define IDM_TRAY_TAKE_MONITOR 171
#define IDM_TRAY_TAKE_WINDOW 172
#define IDM_TRAY_TAKE_REGION 173
#define IDM_TRAY_WEBSITE 174
#define IDM_TRAY_ABOUT 175
#define IDM_TRAY_EXIT 176

// Settings Menu
#define IDM_STARTMINIMIZED_CHK 177
#define IDM_LOADONSTARTUP_CHK 178
#define IDM_COPYTOCLIPBOARD_CHK 179
#define IDM_DISABLEDELAY 180
#define IDM_PLAYSOUNDS_CHK 181
#define IDM_INCLUDEMOUSECURSOR_CHK 182
#define IDM_INCLUDEWINDOWSHADOW_CHK 183
#define IDM_CLEARBACKGROUND_CHK 184
#define IDM_DISABLEAEROONWND_CHK 185
#define IDM_FILENAME_INDEX 186
#define IDM_FILENAME_DATE 187
#define IDM_DELAY_DISABLE 188
#define IDM_HOTKEYS 189

// Region Menu
#define IDM_REGION_START 190
#define IDM_REGION_CANCEL 191

#define IDX_LANGUAGE 1000
#define IDX_FORMATS 2000
#define IDX_DELAY 3000

// Strings
#define IDS_UPDATE_NO 1
#define IDS_UPDATE_YES 2

#define IDS_FILE 3
#define IDS_EXPLORE 4
#define IDS_EXIT 5
#define IDS_VIEW 6
#define IDS_LANGUAGE 7
#define IDS_SETTINGS 8

#define IDS_HELP 9
#define IDS_WEBSITE 10
#define IDS_CHECKUPDATES 11
#define IDS_ABOUT 12
#define IDS_DONATE 13

#define IDS_TRAY_SHOW 14

#define IDS_ALWAYSONTOP_CHK 15
#define IDS_HIDEME_CHK 16
#define IDS_CLASSICUI_CHK 17

#define IDS_STARTMINIMIZED_CHK 18
#define IDS_LOADONSTARTUP_CHK 19
#define IDS_CHECKUPDATES_CHK 20
#define IDS_COPYTOCLIPBOARD_CHK 21
#define IDS_DISABLEAEROONWND_CHK 22

#define IDS_PLAYSOUNDS_CHK 23
#define IDS_INCLUDEMOUSECURSOR_CHK 24
#define IDS_CLEARBACKGROUND_CHK 25

#define IDS_MODE_FULLSCREEN 26
#define IDS_MODE_WINDOW 27
#define IDS_MODE_REGION 28

#define IDS_IMAGEFORMAT 29
#define IDS_FOLDER 30
#define IDS_QUICKSETTINGS 31
#define IDS_MODE 32
#define IDS_SCREENSHOT 33
#define IDS_HOTKEYS 34

#define IDS_DISABLE 35
#define IDS_WARNING_HOTKEYS 36

#define IDS_SAVE 37
#define IDS_CANCEL 38
#define IDS_CLOSE 39

#define IDS_FILENAME 40

#define IDS_UPDATE_ERROR 41
#define IDS_UPDATE_DOWNLOAD 42
#define IDS_UPDATE_DONE 43
#define IDS_UPDATE_INIT 44
#define IDS_UPDATE_INSTALL 45

#define IDS_INCLUDEWINDOWSHADOW_CHK 46
#define IDS_GENERAL 47
#define IDS_LANGUAGE_HINT 48

#define IDS_RESET 49

#define IDS_DELAY 50

#define IDS_MODE_MONITOR 51

// Wav
#define IDW_MAIN 1

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
